### PR TITLE
Order status without auth

### PR DESCRIPTION
**Pull request by davidg43**
## Description
Now its possible to follow the status of an order, when someone pay an order the app will give him the order id and the link to see these information. Also, there is a button with a redirection to this page.

Alert:  IT IS NOT CONTROLLED THE ACCESS TO THE ORDERS. f.e.: One user can saw the order info of the ID X with any control

## Related Issue
https://github.com/NEXUS-PGPI/ardueshop/issues/45

## Screenshots
image

## Checklist
- [x] I have tested the changes locally.
- [x] Documentation has been updated as needed.
- [ ] All necessary reviewers have approved the code.

### CODE REVIEW

**Review by alvarobernal2412 — CHANGES_REQUESTED** [review]
Captura de pantalla 2023-12-05 a las 16 03 42

Due to this typo it is impossible to test the feature

**Review by alvgonfri — COMMENTED** [review]
You should solve the conflicts by merging `develop` into `feature/45-Following-order-without-auth`.

**Review by alvarobernal2412 — CHANGES_REQUESTED** [review]
Error while paying the order, it looks like some endif is missing.
Captura de pantalla 2023-12-06 a las 9 21 34

**Comment by davidg43** [comment]
New commit solving this issue.

Uploading Grabación 2023-12-07 185602.mp4…

**Review by alvgonfri — APPROVED** [review]
Now, everything looks correct.

**Pull request merged**
