### PR TITLE
feat: Manage sales #58

### LINKED ISSUE #58: Gestión de ventas

### PR DESCRIPTION
**Pull request by sebasruii**
## Description
Now admins can find useful sales information by accessing "Administración>Gestión de ventas"
## Related Issue
closes #58 
## Screenshots
image

## Checklist
- [x] I have tested the changes locally.
- [x] Documentation has been updated as needed.
- [ ] All necessary reviewers have approved the code.

### CODE REVIEW

**Review by alvgonfri — COMMENTED** [review]
It looks great, but i think you should use the `order.get_total_cost()` function instead of `order.get_order_cost()`. The `order.get_total_cost()` function also counts shipping costs.

**Comment by sebasruii** [comment]
That is true, it is now updated.

**Review by alvgonfri — APPROVED** [review]
Everything is correct now

**Review by alvarobernal2412 — APPROVED** [review]
Captura de pantalla 2023-12-10 a las 10 56 27
Sales management view correctly implemented.

**Pull request merged**
